### ISSUE TITLE
add  plugin error 

### ISSUE THREAD

**Issue by wujunze** [czcaiwj/calendar#29]
你好:
按照文档的步骤    添加页面的.json配置后报错   帮忙看下 Thanks

jsEnginScriptError
Component is not found in path "pages/about/plugin:/calendar/calendar" (using by "pages/about/about")
Error: Component is not found in path "pages/about/plugin:/calendar/calendar" (using by "pages/about/about")
    at e (http://127.0.0.1:51225/appservice/__dev__/WAService.js:12:8473)
    at e (http://127.0.0.1:51225/appservice/__dev__/WAService.js:12:8625)
    at F (http://127.0.0.1:51225/appservice/__dev__/WAService.js:12:14589)
    at Object.t.addView (http://127.0.0.1:51225/appservice/__dev__/WAService.js:12:15599)
    at Function.value (http://127.0.0.1:51225/appservice/__dev__/WAService.js:14:6004)
    at I (http://127.0.0.1:51225/appservice/__dev__/WAService.js:13:17130)
    at L (http://127.0.0.1:51225/appservice/__dev__/WAService.js:13:19036)
    at U (http://127.0.0.1:51225/appservice/__dev__/WAService.js:13:19590)
    at Function.<anonymous> (http://127.0.0.1:51225/appservice/__dev__/WAService.js:13:21986)
    at http://127.0.0.1:51225/appservice/__dev__/WAService.js:13:27020

**Comment by wujunze** [comment]
已经解决了
